"""
ADK Input Schema Models
Pydantic-based input data structures for each agent
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Literal
from enum import Enum


class LengthPreference(str, Enum):
    """Video length preference options"""
    SHORT = "30-45s"
    MEDIUM = "60-90s" 
    LONG = "2-3min"
    EXTENDED = "3-5min"


class Language(str, Enum):
    """Supported languages"""
    ENGLISH = "English"
    KOREAN = "Korean"
    SPANISH = "Spanish"
    FRENCH = "French"
    GERMAN = "German"
    JAPANESE = "Japanese"


class FullScriptInput(BaseModel):
    """
    Full Script Writer input schema
    Automatically converted to ADK input_schema
    """
    topic: str = Field(
        min_length=5, 
        max_length=200,
        description="Video topic - clear and specific subject matter",
        examples=["Why are dachshunds so short?", "How blockchain technology works"]
    )
    
    length_preference: LengthPreference = Field(
        default=LengthPreference.MEDIUM,
        description="Desired video length"
    )
    
    style_profile: str = Field(
        default="educational and engaging",
        min_length=10,
        description="Overall style and tone",
        examples=["educational and engaging", "serious and informative", "playful and entertaining"]
    )
    
    target_audience: str = Field(
        default="general",
        description="Target audience",
        examples=["general", "students", "professionals", "children"]
    )
    
    language: Language = Field(
        default=Language.ENGLISH,
        description="Content language"
    )
    
    knowledge_refs: Optional[List[str]] = Field(
        default=None,
        description="Reference materials (URLs, papers, books, etc.)",
        examples=[
            ["https://example.com/research", "Smith et al. (2023) Nature Paper"]
        ]
    )

    class Config:
        """Pydantic configuration"""
        json_schema_extra = {
            "title": "FullScriptInput",
            "description": "Input data structure for Full Script Writer Agent"
        }


class SceneExpansionInput(BaseModel):
    """
    Scene Script Writer input schema
    Takes FSW output and expands into detailed scenes
    """
    scene_data: Dict[str, Any] = Field(
        description="Scene beat data generated by FSW",
        examples=[{
            "scene_number": 1,
            "scene_type": "hook",
            "beats": ["Introduce surprising fact about topic"],
            "learning_objectives": ["Capture viewer attention"],
            "needs_animation": True,
            "scene_importance": 5
        }]
    )
    
    global_context: Dict[str, Any] = Field(
        description="Global context (character, style, constraints)",
        examples=[{
            "main_character": "Glowbie",
            "cosplay_instructions": "Scientist with lab coat",
            "overall_style": "educational and engaging",
            "target_audience": "general"
        }]
    )
    
    previous_scenes: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Previous scenes for continuity (optional)"
    )
    
    educational_enhancement_guidelines: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Educational enhancement guidelines"
    )

    class Config:
        json_schema_extra = {
            "title": "SceneExpansionInput", 
            "description": "Input data structure for Scene Script Writer Agent"
        }


class ImageGenerationInput(BaseModel):
    """
    Image Create Agent input schema
    Takes SSW visual specifications to generate images
    """
    visual_specs: List[Dict[str, Any]] = Field(
        min_length=1,
        description="Visual frame specifications",
        examples=[[{
            "frame_id": "1A",
            "shot_type": "medium",
            "image_prompt": "Educational scene with Glowbie character explaining concept",
            "aspect_ratio": "16:9",
            "character_pose": "pointing to diagram",
            "background": "classroom setting"
        }]]
    )
    
    session_id: str = Field(
        description="Session ID (determines file storage path)",
        pattern=r"^\d{8}-[a-f0-9-]{36}$"
    )
    
    cost_saving_mode: bool = Field(
        default=False,
        description="Cost-saving mode (use mock images)"
    )
    
    character_reference: Optional[str] = Field(
        default=None,
        description="Reference image path for character consistency"
    )

    class Config:
        json_schema_extra = {
            "title": "ImageGenerationInput",
            "description": "Input data structure for Image Create Agent"
        }


class VoiceGenerationInput(BaseModel):
    """
    Voice Generate Agent 입력 스키마
    SSW의 나레이션을 받아서 TTS 생성
    """
    scene_packages: List[Dict[str, Any]] = Field(
        min_length=1,
        description="음성을 생성할 씬 패키지들"
    )
    
    session_id: str = Field(
        description="Session ID",
        pattern=r"^\d{8}-[a-f0-9-]{36}$"
    )
    
    voice_settings: Optional[Dict[str, Any]] = Field(
        default=None,
        description="음성 설정 (엔진, 음성, 속도 등)"
    )

    class Config:
        json_schema_extra = {
            "title": "VoiceGenerationInput",
            "description": "Voice Generate Agent의 입력 데이터 구조"
        }


class VideoAssemblyInput(BaseModel):
    """
    Video Maker Agent 입력 스키마
    모든 에셋을 받아서 최종 비디오 조립
    """
    session_id: str = Field(
        description="Session ID",
        pattern=r"^\d{8}-[a-f0-9-]{36}$"
    )
    
    image_assets: List[Dict[str, Any]] = Field(
        description="이미지 에셋들"
    )
    
    voice_assets: List[Dict[str, Any]] = Field(
        description="음성 에셋들"
    )
    
    scene_packages: List[Dict[str, Any]] = Field(
        description="타이밍 정보가 포함된 씬 패키지들"
    )
    
    video_settings: Optional[Dict[str, Any]] = Field(
        default=None,
        description="비디오 설정 (해상도, FPS, 품질 등)"
    )

    class Config:
        json_schema_extra = {
            "title": "VideoAssemblyInput",
            "description": "Video Maker Agent의 입력 데이터 구조"
        }
